export const commonSelectors = {
  launchBotButton: "div.new-message-bot-commands-view",
  authLoginPage: "div.tabs-container.auth-pages__container",
};

export const blumBotSelectors = {
  backButton: "div._BrowserHeader_m63td_55 > button:nth-child(1)",
  balanceLabel: "div.profile-with-balance > div.balance > div",
  boostSelector: "div.popup.popup-peer.popup-boost.active > div > div.popup-buttons > button:nth-child(2)",
  buttonSelector: "div.kit-fixed-wrapper.no-layout-tabs > button",
  claimButton: "div.kit-fixed-wrapper > div.index-farming-button > button.kit-button",
  claimButtons: " div.tasks-list button.is-status-ready-for-claim",
  closeBotButton: "div._BrowserHeader_m63td_55 > button:nth-child(1)",
  closeWalletSelector: "#tc-widget-root > tc-root > div > div > div > button",
  continueButton: "div.kit-fixed-wrapper > button",
  continueButtonPrimary: "button.kit-button.is-large.is-primary",
  earnButton: "#app > div.layout-tabs.tabs > a:nth-child(2)",
  earnTitleSelector: "div.tasks-page.page .title",
  homeButton: "div.layout-tabs.tabs > a:nth-child(1)",
  inputSelector: "div.kit-input.input > div > label > input",
  listTasks: " div.tasks-list button.is-status-not-started",
  lists: "div.kit-tabs.is-inline label.kit-tab.is-inline",
  playButton: "div.pages-index-drop.drop-zone > div > a",
  ticketLabel: "div.title-with-balance > div.pass",
  verifyTasks: " div.tasks-list button.is-status-ready-for-verify",
  weeklyTasksDone: "div.pages-tasks-card.is-short div.done-icon",
  weeklyTasks: "div.pages-tasks-card.is-short button.is-status-not-started",
  weeklyTasksList: "div.nested-tasks > div.pages-tasks-list-item-label button.is-status-not-started",
  weeklyTasksListClaim: "div.nested-tasks > div.pages-tasks-list-item-label button.is-status-ready-for-claim",
  weeklyTasksListClose: "div.kit-bottom-sheet > dialog > div.header > div.right-slot > button.close-btn",
};

export const tapswapBotSelectors = {
  backButton: " div._BrowserHeader_m63td_55 > button:nth-child(1)",
  checkButton: "div._listContainer_1519s_1 > div > div > button._button_fffa0_1",
  claimButton: "div._actionContent_1v85a_75 > button._button_fffa0_1",
  claimPriceButton: "div._actionContent_1v85a_75 > button._button_fffa0_1._primary_fffa0_13._large_fffa0_49._fullWidth_fffa0_37",
  claimTaskButton: "button._button_fffa0_1",
  finishMission: "button._button_fffa0_1._secondary_fffa0_21._large_fffa0_49",
  nameOfTask: "h3._h3_1a2e0_1",
  startMission: "button._button_fffa0_1._secondary_fffa0_21._large_fffa0_49",
  submitButton: "div._answer_box_l4h9d_35 > button._button_fffa0_1",
  successClaimMission2M: "div._desc_1gncg_40 > p._body1_ytgu1_1",
  totalText: "p._body3_xgldm_1",
  videoBaseListItem: "div._container_jn9s0_1 > div._tabsContainer_1pooj_1 > div._listContainer_1519s_1 > button:nth-child",
  videoContainer: "div._listContainer_1519s_1",
  videoCount: "div._balance_1cln7_20 > p._body3_xgldm_1",
  videoTabButton: "div._wrapper_1z04b_1 > button:nth-child(2)",
  watchButton: "a._link_l4h9d_25 > button._button_fffa0_1._secondary_fffa0_21._small_fffa0_41",
};

export const pixelGameSelectors = {
  promiseButton: "div._button_container_1boq4_54 > button._button_1boq4_54",
  goButton: "div._button_container_1drph_81 > button._button_1drph_81",
  crashGame: "div._container_ieygs_8",
  balanceLabel: "div._group_184v8_8._middle_184v8_21 > button._button_184v8_1 > div > div._number_jcaqa_1",
  claimSelector: "div._content_1mmx9_21 > div._container_3i6l4_1 > button._button_3i6l4_11",
  waitClaimSelector: "div._content_1mmx9_21 > div._container_3i6l4_1 > div._info_3i6l4_32",
  boostsSelector: "div._content_1mmx9_21 > div._panel_1mia4_1 > div:nth-child(2)",
  tasksSelector: "div._content_1mmx9_21 > div._panel_1mia4_1 > div:nth-child(1)",
  paintRewardsSelector: "div._info_layout_bt2qf_1 > div > div._group_v8prs_7 > div:nth-child(1)",
  rechargingSelector: "div._info_layout_bt2qf_1 > div > div._group_v8prs_7 > div:nth-child(2)",
  energyLimitSelector: "div._info_layout_bt2qf_1 > div > div._group_v8prs_7 > div:nth-child(3)",
};
